services:
  nats-server:
    image: nats:2.9.25
    ports:
      - 8222:8222

  orders-db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-microservice/postgres:/var/lib/postgresl/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=orders

  client-gateway:
    build: ./client-gateway
    ports:
      - ${GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3000

  products-microservice:
    build: ./products-microservice
    volumes:
      - ./products-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3001

  orders-microservice:
    depends_on:
      - orders-db
    build: ./orders-microservice
    volumes:
      - ./orders-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/orders?schema=public
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3002
