services:
  nats-server:
    image: nats:2.9.25
    ports:
      - 8222:8222

  orders-db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-microservice/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=orders

  client-gateway:
    depends_on:
      - nats-server
      - orders-db
    build: ./client-gateway
    ports:
      - ${GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3000

  auth-microservice:
    build: ./auth-microservice
    volumes:
      - ./auth-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222
      - JWT_SECRET=${JWT_SECRET}

  products-microservice:
    depends_on:
      - client-gateway
    build: ./products-microservice
    volumes:
      - ./products-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3001

  orders-microservice:
    depends_on:
      - orders-db
      - products-microservice
    build: ./orders-microservice
    volumes:
      - ./orders-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/orders?schema=public
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3002

  payments-microservice:
    depends_on:
      - orders-microservice
    build: ./payments-microservice
    volumes:
      - ./payments-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=${PAYMENTS_MICROSERVICE_PORT}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
    ports:
      - ${PAYMENTS_MICROSERVICE_PORT}:${PAYMENTS_MICROSERVICE_PORT}
